<template>
	<ge-page :tabs="tabs" :tab-active="0" :no-tabs="false" @tap-tabbar="tapTabbar" tab-transparent
		:background-image="`url('https://mp-093771b9-58d4-4c63-982d-8d3dc351dede.cdn.bspapp.com/pics/paint_flowers.jpg')`">
		<ge-navbar hide-back :opacity="false" custom-left title="正在播放我喜爱的" fix-content>
			<template v-slot:customLeft>
				<view @tap="closePlay">
					<ge-avatar icon name="ph ph-caret-down" round size="sm" no-border></ge-avatar>
				</view>
			</template>
			<template v-slot:fixContent>
				<view style="width: 100%;">
					<ge-navlist transparent :items="items" type="button"></ge-navlist>
				</view>
			</template>
		</ge-navbar>

		<image style="width: 100%; height:520rpx" mode="aspectFill"
			src="https://mp-093771b9-58d4-4c63-982d-8d3dc351dede.cdn.bspapp.com/pics/paint_flowers-cover.jpg" />
		<view class="ui-container">
			<view class="ablum-info">
				<view class="ablum-title">
					<text class="main">一朵美丽的花🌼</text>
					<text class="sub">Picture generated by Midjourney</text>
				</view>
				<view class="ablum-buttons">
					<view class="ablum-button"><text class="ph ph-info"></text></view>
					<view class="ablum-button"><text class="ph ph-heart"></text></view>
				</view>
			</view>

			<slider class="margin-top" :value="30" :block-size="15"
				:block-color="system_theme === 'dark' ? '#00B670' : '#000'"
				:active-color="system_theme === 'dark' ? '#00B670' : '#4376FE'"
				:background-color="system_theme === 'dark' ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.2)'">
			</slider>
			<view class="ablum-play-time">
				<text class="now-time" :style="[{color: system_theme === 'dark' ? '#00B670' : '#4376FE'}]">00:13</text>
				<text class="total-time">04:20</text>
			</view>

			<view class="play-controller">
				<view class="controller level-one"><text class="ph ph-shuffle"></text></view>
				<view class="controller level-two"><text class="ph ph-skip-back"></text></view>
				<view class="controller level-three"><text class="ph ph-play-pause"></text></view>
				<view class="controller level-two"><text class="ph ph-skip-forward"></text></view>
				<view class="controller level-one"><text class="ph ph-repeat"></text></view>
			</view>

			<view style="border-radius: 24rpx;"
				:style="[{backgroundColor: system_theme === 'dark' ? '#000' : 'rgba(255, 255, 255, 0.5)'}]">
				<view class="player-tips"
					:style="[{backgroundColor: system_theme === 'light' ? 'rgba(67, 118, 254, 0.1)' : 'rgba(67, 118, 254, 0.38)'}]">
					<view class="icon">
						<text class="ph ph-medal"></text>
					</view>
					<view class="content">
						<view class="title">加入会员开启无损音质</view>
						<view class="subtitle">免费试用7天</view>
					</view>
					<view class="op">
						<view class="ph ph-x"></view>
					</view>
				</view>
			</view>
		</view>
	</ge-page>
</template>
<script>
	export default {
		data() {
			return {
				tabs: [{
						'name': '播放列表',
						'url': '',
						'click': 'switch',
						'icon': 'ph ph-play-circle',
						'notification': false,
						'type': 'icon'
					},
					{
						'name': '我的信息',
						'url': '',
						'click': 'switch',
						'icon': 'ph ph-user-circle',
						'notification': false,
						'type': 'icon'
					},
					{
						'name': '设置',
						'url': '',
						'click': 'switch',
						'icon': 'ph ph-gear',
						'notification': false,
						'type': 'icon'
					}
				],
				items: [
					'我喜爱的',
					'流行',
					'爵士',
					'电子'
				]
			}
		},
		methods: {
			closePlay() {
				uni.switchTab({
					url: '/pages/index/index'
				});
			}
		}
	}
</script>
<style lang="scss" scoped>
	.ablum-info {
		margin-top: 80rpx;
		height: 128rpx;
		width: 100%;
		gap: 16rpx;
		display: flex;
		align-items: center;
		position: relative;

		.ablum-title {
			display: flex;
			justify-content: center;
			flex-direction: column;

			.main {
				font-size: 32rpx;
				font-style: normal;
				font-weight: 400;
				line-height: 150%;
				letter-spacing: 0.269px;
			}

			.sub {
				font-size: 28rpx;
				font-style: normal;
				font-weight: 400;
				line-height: 142%;
				letter-spacing: 0.235px;
				color: var(--ui-text-regular-3);
			}
		}


		.ablum-buttons {
			position: absolute;
			right: 0;
			display: flex;
			gap: 16rpx;

			.ablum-button {
				height: 70rpx;
				width: 110rpx;
				border-radius: 999rpx;
				display: flex;
				align-items: center;
				justify-content: center;
				// background-color: rgba(0, 0, 0, 0.1);
				background-color: var(--ui-bg-glass);
				font-size: 36rpx;
			}
		}
	}

	.ablum-play-time {
		position: relative;
		width: 100%;
		height: 48rpx;
		vertical-align: center;

		.now-time {
			position: absolute;
			left: 0;
			font-size: 32rpx;
			font-style: normal;
			font-weight: 400;
			line-height: 150%;
			/* 24px */
			letter-spacing: 0.269px;
		}

		.total-time {
			position: absolute;
			right: 0;
			font-size: 32rpx;
			font-style: normal;
			font-weight: 400;
			line-height: 150%;
			/* 24px */
			letter-spacing: 0.269px;
			color: var(--ui-text-regular-3);
		}
	}

	.play-controller {
		position: relative;
		width: 100%;
		height: 144rpx;
		display: flex;
		align-items: center;
		justify-content: space-between;

		.controller {
			border-radius: 999rpx;
			display: flex;
			align-items: center;
			// background-color: rgba(0, 0, 0, 0.1);
			background-color: var(--ui-bg-glass);
			justify-content: center;

			&.level-one {
				height: 80rpx;
				width: 80rpx;
			}

			&.level-two {
				height: 96rpx;
				width: 96rpx;
				font-size: 36rpx;
			}

			&.level-three {
				height: 112rpx;
				width: 112rpx;
				font-size: 44rpx;
			}
		}
	}

	/deep/ slider {
		margin: 6rpx 0;

		.wx-slider-thumb {
			border: 1px solid #FFF;
		}
	}

	/deep/ uni-slider .uni-slider-thumb {
		border: 1px solid #FFF;
	}

	.player-tips {
		height: 160rpx;
		width: 100%;
		display: flex;
		align-items: center;
		position: relative;
		border-radius: 23rpx;
		margin-top: 48rpx;

		.icon {
			width: 77rpx;
			height: 77rpx;
			display: flex;
			align-items: center;
			justify-content: center;
			color: #FE8E0B;
			font-size: 58rpx;
			position: relative;
			margin-left: 23rpx;
		}

		.op {
			font-size: 40rpx;
			color: var(--ui-text-regular-2);
			position: absolute;
			right: 48rpx;
		}

		.content {
			position: relative;
			padding-left: 23rpx;

			.title {
				font-style: normal;
				font-weight: 600;
				font-size: 32rpx;
				line-height: 150%;
			}

			.subtitle {
				ont-style: normal;
				font-weight: 400;
				font-size: 28rpx;
				line-height: 142%;
				color: #FE8E0B;
			}
		}
	}
</style>